[package]
name = "rtc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.4"
image = "0.24.7"
indicatif = "0.17.6"
rayon = "1.7.0"
imgui = "0.11.0"
